[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pythonCalculator"
authors = [{name = "Carsten Hennig", email = "carsten.hennig@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "http://about.me/carsten.hennig"
